name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检查代码
        uses: actions/checkout@v2

      - name: 检查版本文件
        id: check_version_file
        run: |
          if [ -f version.json ]; then
            echo "版本文件已存在"
            echo "当前版本："
            cat version.json
          else
            echo "版本文件不存在，创建版本文件..."
            echo "{\"version\": \"2.1.0\"}" > version.json
            echo "已创建版本文件，当前版本："
            cat version.json
          fi

      - name: 确认用户账户
        run: |
          git config --global user.email "shanshui2024@github.com"
          git config --global user.name "Auto Update"
        
      - name: 确定版本号和新版本
        id: determine_version
        run: |
          python determine_version.py
        working-directory: .
        
      - name: 更新版本
        run: |
          echo "正在更新版本信息..."
          sed -i -e 's/"version": ".*"/"version": "'${{ steps.determine_version.outputs.new_version }}'"/' version.json

      - name: 显示版本
        run: |
          echo "当前版本号：${{ steps.determine_version.outputs.current_version }}"
          echo "新版本号：${{ steps.determine_version.outputs.new_version }}"

      - name: 提交更改
        run: |
          git add .
          version=$(python determine_version.py)
          git commit -m "版本更新：$version"
          git push
