name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 检查代码
      uses: actions/checkout@v2
    - name: 创建版本文件
      run: |
        if [ ! -f your_json_file.json ]; then
          echo "{\"version\": \"2.1.0\"}" > version.json
        fi
    - name: Configure Git user
      run: |
        git config --global user.email "autoload@github.com"
        git config --global user.name "Auto Actions"
    - name: 确定版本号和新版本号
      id: determine_version
      run: |
        # 在此处编写Python脚本或使用其他方法来确定新版本号
        version=$(python determine_version.py)
        echo "::set-output name=version::${version}"
      
    - name: 更新版本
      run: |
        echo "正在更新版本信息..."
        sed -i 's/"version": ".*"/"version": "${{ steps.determine_version.outputs.version }}"/' version.json

    - name: 提交更改
      env:
        SSH_PRIVATE_KEY: ${{ secrets.UPDATE }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --local core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
        git add .
        git commit -m "版本更新"
        git push
